services:
  mysql:
    image: mysql:8.4
    container_name: community-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: community_db
      MYSQL_USER: community
      MYSQL_PASSWORD: community1234
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.4
    container_name: community-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: community-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: community
      RABBITMQ_DEFAULT_PASS: community1234
    ports:
      - "5672:5672"
      - "15672:15672"
